name: geopoint
author: synw <ansterj@gmail.com>
description: Geospatial data structures. Provides GeoPoint and GeoSerie models.
homepage: https://github.com/synw/geopoint
version: "0.4.1"

environment:
  sdk: ">=2.0.0 <3.0.0"
  
dependencies:
  meta: ^1.1.6
  latlong: ^0.6.1
  slugify2: ^0.2.1
  pedantic: ^1.4.0

dev_dependencies:
  test: ^1.5.1+1
  test_coverage: ^0.2.3
