name: geopoint
author: synw <synwe@yahoo.com>
description: Data structures and methods for Geolocator. Provides a GeoPoint and GeoSerie models with various constructors and methods.
homepage: https://github.com/synw/geopoint
version: "0.1.1"

environment:
  sdk: ">=2.0.0 <3.0.0"
  
dependencies:
  latlong: ^0.6.1
  slugify2: ^0.2.0

dev_dependencies:
  test: any
