name: geopoint
author: synw <ansterj@gmail.com>
description: Geospatial data structures. Provides GeoPoint and GeoSerie models.
homepage: https://github.com/synw/geopoint
version: 0.7.1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  pedantic: ^1.8.0
  extra_pedantic: ^1.1.1+3
  meta: ^1.1.8
  latlong: ^0.6.1
  slugify2: ^0.2.1

dev_dependencies:
  test: ^1.6.5
  test_coverage: ^0.4.1
